### ISSUE TITLE
Autoload without Composer

### ISSUE THREAD

**Issue by markroland** [aferrandini/PHPQRCode#14]
I'm trying to use this in a legacy application that doesn't use Composer. Can you provide an example of how to use this without Composer's autoloading?

**Comment by bradchesney79** [comment]
Go see it on the sourceforge ( http://phpqrcode.sourceforge.net/ ), instructions for old school loading there. If I remember correctly it was just making the library available to your PHP process and including/requiring the one file, qrlib.php, in your script.

**Comment by markroland** [comment]
Thank you for the response, I appreciate it. I was trying that but not having success. I've ended up using a different library.
