### ISSUE TITLE
The original png() etc... methods should also return resources

### ISSUE THREAD

**Issue by GiacomoP** [aferrandini/PHPQRCode#15]
Thanks for this awesome version compatible with Composer.

In a project I'm working on I was switching from the regular version of PHPQRCode and this one, but I can't find a way to get the QRCode as a resource.

We were using the function png() with the $filename parameter set to false. The original library would have in its code:
`if ($filename === false) { return $image; } [...]`

While this one prints it, which is not the correct behavior.

The file is QRimage.php

I see that in QRcode.php, png() correctly make a return of whatever the encoding step produces, but then QRencode::encodePNG() and QRimage::png() won't return anything.

Is this an issue or I'm just missing something? If it is I can make a pull request.

**Comment by rogiermulders** [comment]
:) I have about the same issue I guess

**Comment by aferrandini** [comment]
@GiacomoP Sorry for my silence, this package is abandoned. Please use `endroid/qr-code` instead.
