### ISSUE TITLE
Fatal error: Call to undefined function PHPQRCode\ImageCreate()

### ISSUE THREAD

**Issue by awesomeUA** [aferrandini/PHPQRCode#16]
Fatal error: Call to undefined function PHPQRCode\ImageCreate()

any ideas?

**Comment by EneasVVA** [comment]
yes, it's because GD library is mandatory.

**Comment by aferrandini** [comment]
@aferrandini Sorry for my silence, this package is abandoned. Please use `endroid/qr-code` instead.
