### ISSUE TITLE
QRimage::image is private (not clear how to get a binary image)

### ISSUE THREAD

**Issue by rogiermulders** [aferrandini/PHPQRCode#17]
QRimage::image is a private static function.

I need the raw image data for an email attachment.
It is not clear to me how to get a binary image other than hacking the private function.

Two solutions maybe. 
a) If there is a way to get the raw image make it more clear how to do that.
b) Just make QRimage::image public. Users should know what to do with it.

**Comment by aferrandini** [comment]
@rogiermulders Sorry for my silence, this package is abandoned. Please use `endroid/qr-code` instead.
